---
- name: >
    PLAYBOOK - "workshop_lab_part_1.yml" (F5-BIGIP Automation via SSH on 
    multiple environments using Ansible inventory files)
  hosts: all
  gather_facts: no
  tasks:

  - name: > 
      1. Testing the SSH connection to the [{{ inventory_hostname }}] 
      F5-BIGIP device from the 
      [{{ inventory_file|regex_replace(playbook_dir,'') }}] inventory
    ansible.builtin.ping:

  - name: >
      2. Gathering all the balanced services created for the
      [{{ inventory_hostname }}] F5-BIGIP device from the 
      [{{ inventory_file|regex_replace(playbook_dir,'') }}] inventory via 
      SSH
    ansible.builtin.shell:
      cmd: >-
        tmsh list ltm virtual creation-time description |
        grep -A 1 '{{ date_stats }}' |
        grep '{{ automation_id }}' -c
    register: results
    ignore_errors: true

  - name: 3. SHOW RESULTS
    debug:
      msg: >-
        total balanced services created on [{{ date_stats }}] =
        [{{ results.stdout|default(none) }}]
...
