---
- name: >
    PLAYBOOK - "workshop_lab_part_1.yml" (F5-BIGIP Automation via SSH on 
    multiple environments using Ansible inventory files)
  hosts: all
  gather_facts: no
  tasks:

  - name: > 
      1.1. Pinging [{{ ansible_host }}] device / server from the
      [{{ devices_environment }}] environment
    ansible.builtin.ping:

  - name: >
      2.1. Gathering all the balanced services created for the
      [{{ ansible_host }}] from the [{{ devices_environment }}]
      environment via SSH
    ansible.builtin.shell:
      cmd: tmsh list ltm virtual creation-time description | grep -A 1 '{{ date_stats }}' | grep '{{ automation_id }}' -c
    register: results
    ignore_errors: true

  - name: 2.2. SHOW RESULTS
    debug:
      msg: >
        total balanced services created on [{{ date_stats }}] =
        [{{ results.stdout|default(none) }}]
...
