---
- name: >
    PLAYBOOK - "workshop_lab_part_2.yml" (F5-BIGIP Automation via REST
    on multiple environments using Ansible inventory files)
  hosts: all
  vars_files:
    - "{{ playbook_dir + vault_file }}"
  gather_facts: false
  tasks:

    - name: >
        1. Gathering all the balanced services created for the
        [{{ inventory_hostname }}] F5-BIGIP device from the
        [{{ inventory_file | regex_replace(playbook_dir, '') }}] inventory
        via REST
      f5networks.f5_modules.bigip_command:
        provider: "{{ f5_provider }}"
        commands: >-
          list ltm virtual creation-time description |
          grep -A 1 '{{ date_stats }}' |
          grep '{{ automation_id }}' -c
      register: results
      delegate_to: localhost
      ignore_errors: true

    - name: 2. SHOW RESULTS
      ansible.builtin.debug:
        msg: >-
          total balanced services created on [{{ date_stats }}] =
          [{{ results.stdout | default(none) }}]
...
